# Generated by Django 4.0.4 on 2022-05-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alvo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campos',
            table='Campos',
        ),
    ]
