# Generated by Django 4.0.4 on 2022-05-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alvo', '0003_rename_campos_alvo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alvo',
            table='Alvo',
        ),
    ]
